### ISSUE TITLE
xps/obj/gxps: No such file or directory

### ISSUE THREAD

**Issue by balupton** [sri/xps2pdf#2]
```
fixing the makefile...
compiling...
converting
  Alinta - 2008-08-11.xps =>
  Alinta - 2008-08-11.pdf
sh: /tmp/xps2pdf.tmp/ghostpdl-9.02/xps/obj/gxps: No such file or directory
```

**Comment by balupton** [comment]
when I cd into the `ghostpdl-9.02` directory and run `make xps` myself, all I get is `make: Nothing to be done for 'xps'` - doesn't seem there is a Makefile in that directory either.

**Comment by balupton** [comment]
got it working by:

1. downloading the ghostpdl source from https://ghostscript.com/download/gxpsdnld.html
2. extract it
3. cd into it
4. `./configure`
5. `make`
6. update the script as such

``` ruby
#! /usr/bin/env ruby
# Converts Microsoft's XPS to PDF using Ghostscript.
# Tested on Mac OS X.
# Require Ruby 1.9.2.
# Automatically downloads Ghostscript, compiles it (with a
# small fix), and converts all the list XPS files.
# Usage: ruby xps2pdf.rb [XPS files or dirs]

def main
  xps      = "/Users/balupton/bin/xps2pdf.tmp/ghostpdl-9.20/bin/gxps"
  convert  = "#{xps} -sDEVICE=pdfwrite -sOutputFile='%s' -dNOPAUSE '%s'"

  ARGV.each do |xps|
    pdf = xps.gsub(/[.]xps$/, '.pdf')
    if File.exists?(pdf)
      puts "skipping existing #{pdf}"
    else
      cmd = convert % [pdf, xps]
      puts "converting\n  #{xps} =>\n  #{pdf}"
      `#{cmd}`
    end
  end
rescue
  puts "error: #{$!}"
end

if $0 == __FILE__
  main
end
```

works great!

**Comment by balupton** [comment]
would be nice if the ctime was the same as the source file

**Comment by balupton** [comment]
alright, accomplished it with bash https://gist.github.com/balupton/7f15f6627d90426f12b24a12a4ac5975

**Comment by sri** [comment]
Thanks for reporting this! Looks like the executable changed from
`/tmp/xps2pdf.tmp/ghostpdl-9.02/xps/obj/gxps` to
`/tmp/xps2pdf.tmp/ghostpdl-9.20/bin/gxps`
Will change that when I get to it!
-Sriram
